<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        if (!Schema::hasTable('transmuted_grade')) {
            Schema::create('transmuted_grade', function (Blueprint $table) {
                $table->id();

                $table->decimal('score_bracket', 5, 2);

                $table->decimal('score', 5, 2);

                $table->decimal('transmuted_grade', 5, 2);

                $table->timestamps();
            });


            DB::table('transmuted_grade')->insert([
                ['score_bracket' => '10.00', 'score' => '10.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '10.00', 'score' => '9.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '10.00', 'score' => '8.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '10.00', 'score' => '7.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '10.00', 'score' => '6.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '10.00', 'score' => '5.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '10.00', 'score' => '3.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '10.00', 'score' => '2.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '10.00', 'score' => '0.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],

                ['score_bracket' => '20.00', 'score' => '20.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '20.00', 'score' => '19.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '20.00', 'score' => '18.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '20.00', 'score' => '17.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '20.00', 'score' => '16.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '20.00', 'score' => '15.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '20.00', 'score' => '14.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '20.00', 'score' => '13.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '20.00', 'score' => '12.00', 'transmuted_grade' => '3.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '20.00', 'score' => '11.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '20.00', 'score' => '6.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '20.00', 'score' => '5.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '20.00', 'score' => '0.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],

                ['score_bracket' => '30.00', 'score' => '30.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '30.00', 'score' => '29.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '30.00', 'score' => '28.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '30.00', 'score' => '27.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '30.00', 'score' => '26.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '30.00', 'score' => '25.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '30.00', 'score' => '24.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '30.00', 'score' => '23.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '30.00', 'score' => '22.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '30.00', 'score' => '21.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '30.00', 'score' => '20.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '30.00', 'score' => '19.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '30.00', 'score' => '18.00', 'transmuted_grade' => '3.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '30.00', 'score' => '17.00', 'transmuted_grade' => '3.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '30.00', 'score' => '9.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '30.00', 'score' => '8.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '30.00', 'score' => '0.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],

                ['score_bracket' => '40.00', 'score' => '40.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '40.00', 'score' => '39.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '40.00', 'score' => '38.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '40.00', 'score' => '37.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '40.00', 'score' => '36.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '40.00', 'score' => '35.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '40.00', 'score' => '34.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '40.00', 'score' => '33.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '40.00', 'score' => '32.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '40.00', 'score' => '31.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '40.00', 'score' => '30.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '40.00', 'score' => '29.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '40.00', 'score' => '28.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '40.00', 'score' => '27.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '40.00', 'score' => '26.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '40.00', 'score' => '25.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '40.00', 'score' => '24.00', 'transmuted_grade' => '3.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '40.00', 'score' => '23.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '40.00', 'score' => '12.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '40.00', 'score' => '11.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '40.00', 'score' => '0.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],

                ['score_bracket' => '50.00', 'score' => '50.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '50.00', 'score' => '49.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '50.00', 'score' => '48.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '50.00', 'score' => '47.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '50.00', 'score' => '46.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '50.00', 'score' => '45.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '50.00', 'score' => '44.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '50.00', 'score' => '43.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '50.00', 'score' => '42.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '50.00', 'score' => '41.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '50.00', 'score' => '40.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '50.00', 'score' => '39.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '50.00', 'score' => '38.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '50.00', 'score' => '37.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '50.00', 'score' => '36.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '50.00', 'score' => '35.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '50.00', 'score' => '34.00', 'transmuted_grade' => '3.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '50.00', 'score' => '30.00', 'transmuted_grade' => '3.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '50.00', 'score' => '29.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '50.00', 'score' => '15.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '50.00', 'score' => '14.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '50.00', 'score' => '0.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],

                ['score_bracket' => '60.00', 'score' => '60.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '60.00', 'score' => '58.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '60.00', 'score' => '57.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '60.00', 'score' => '55.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '60.00', 'score' => '54.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '60.00', 'score' => '52.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '60.00', 'score' => '51.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '60.00', 'score' => '49.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '60.00', 'score' => '48.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '60.00', 'score' => '46.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '60.00', 'score' => '45.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '60.00', 'score' => '43.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '60.00', 'score' => '42.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '60.00', 'score' => '40.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '60.00', 'score' => '39.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '60.00', 'score' => '37.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '60.00', 'score' => '36.00', 'transmuted_grade' => '3.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '60.00', 'score' => '35.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '60.00', 'score' => '30.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '60.00', 'score' => '29.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '60.00', 'score' => '0.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],

                ['score_bracket' => '70.00', 'score' => '70.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '70.00', 'score' => '68.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '70.00', 'score' => '67.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '70.00', 'score' => '65.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '70.00', 'score' => '64.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '70.00', 'score' => '62.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '70.00', 'score' => '61.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '70.00', 'score' => '59.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '70.00', 'score' => '58.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '70.00', 'score' => '56.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '70.00', 'score' => '55.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '70.00', 'score' => '53.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '70.00', 'score' => '52.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '70.00', 'score' => '50.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '70.00', 'score' => '49.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '70.00', 'score' => '47.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '70.00', 'score' => '46.00', 'transmuted_grade' => '3.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '70.00', 'score' => '42.00', 'transmuted_grade' => '3.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '70.00', 'score' => '41.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '70.00', 'score' => '21.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '70.00', 'score' => '20.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '70.00', 'score' => '0.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],

                ['score_bracket' => '80.00', 'score' => '80.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '80.00', 'score' => '77.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '80.00', 'score' => '76.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '80.00', 'score' => '73.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '80.00', 'score' => '72.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '80.00', 'score' => '69.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '80.00', 'score' => '68.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '80.00', 'score' => '65.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '80.00', 'score' => '64.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '80.00', 'score' => '61.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '80.00', 'score' => '60.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '80.00', 'score' => '57.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '80.00', 'score' => '56.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '80.00', 'score' => '53.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '80.00', 'score' => '52.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '80.00', 'score' => '49.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '80.00', 'score' => '48.00', 'transmuted_grade' => '3.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '80.00', 'score' => '47.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '80.00', 'score' => '24.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '80.00', 'score' => '23.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '80.00', 'score' => '0.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],

                ['score_bracket' => '90.00', 'score' => '90.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '90.00', 'score' => '87.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '90.00', 'score' => '86.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '90.00', 'score' => '83.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '90.00', 'score' => '82.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '90.00', 'score' => '79.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '90.00', 'score' => '78.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '90.00', 'score' => '75.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '90.00', 'score' => '74.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '90.00', 'score' => '71.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '90.00', 'score' => '70.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '90.00', 'score' => '67.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '90.00', 'score' => '66.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '90.00', 'score' => '63.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '90.00', 'score' => '62.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '90.00', 'score' => '59.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '90.00', 'score' => '58.00', 'transmuted_grade' => '3.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '90.00', 'score' => '54.00', 'transmuted_grade' => '3.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '90.00', 'score' => '53.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '90.00', 'score' => '27.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '90.00', 'score' => '26.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '90.00', 'score' => '0.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],

                ['score_bracket' => '100.00', 'score' => '100.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '100.00', 'score' => '96.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '100.00', 'score' => '95.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '100.00', 'score' => '91.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '100.00', 'score' => '90.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '100.00', 'score' => '86.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '100.00', 'score' => '85.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '100.00', 'score' => '81.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '100.00', 'score' => '80.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '100.00', 'score' => '76.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '100.00', 'score' => '75.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '100.00', 'score' => '71.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '100.00', 'score' => '70.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '100.00', 'score' => '66.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '100.00', 'score' => '65.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '100.00', 'score' => '61.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '100.00', 'score' => '60.00', 'transmuted_grade' => '3.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '100.00', 'score' => '59.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '100.00', 'score' => '30.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '100.00', 'score' => '29.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '100.00', 'score' => '0.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],

                ['score_bracket' => '110.00', 'score' => '110.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '110.00', 'score' => '106.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '110.00', 'score' => '105.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '110.00', 'score' => '101.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '110.00', 'score' => '100.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '110.00', 'score' => '96.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '110.00', 'score' => '95.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '110.00', 'score' => '91.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '110.00', 'score' => '90.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '110.00', 'score' => '86.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '110.00', 'score' => '85.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '110.00', 'score' => '81.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '110.00', 'score' => '80.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '110.00', 'score' => '76.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '110.00', 'score' => '75.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '110.00', 'score' => '71.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '110.00', 'score' => '70.00', 'transmuted_grade' => '3.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '110.00', 'score' => '66.00', 'transmuted_grade' => '3.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '110.00', 'score' => '65.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '110.00', 'score' => '33.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '110.00', 'score' => '32.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '110.00', 'score' => '0.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],

                ['score_bracket' => '120.00', 'score' => '120.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '120.00', 'score' => '115.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '120.00', 'score' => '114.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '120.00', 'score' => '109.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '120.00', 'score' => '108.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '120.00', 'score' => '103.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '120.00', 'score' => '102.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '120.00', 'score' => '97.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '120.00', 'score' => '96.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '120.00', 'score' => '91.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '120.00', 'score' => '90.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '120.00', 'score' => '85.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '120.00', 'score' => '84.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '120.00', 'score' => '79.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '120.00', 'score' => '78.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '120.00', 'score' => '73.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '120.00', 'score' => '72.00', 'transmuted_grade' => '3.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '120.00', 'score' => '71.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '120.00', 'score' => '36.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '120.00', 'score' => '35.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '120.00', 'score' => '0.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],

                ['score_bracket' => '130.00', 'score' => '130.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '130.00', 'score' => '125.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '130.00', 'score' => '124.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '130.00', 'score' => '119.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '130.00', 'score' => '118.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '130.00', 'score' => '113.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '130.00', 'score' => '112.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '130.00', 'score' => '107.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '130.00', 'score' => '106.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '130.00', 'score' => '101.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '130.00', 'score' => '100.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '130.00', 'score' => '95.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '130.00', 'score' => '94.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '130.00', 'score' => '89.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '130.00', 'score' => '88.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '130.00', 'score' => '83.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '130.00', 'score' => '82.00', 'transmuted_grade' => '3.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '130.00', 'score' => '78.00', 'transmuted_grade' => '3.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '130.00', 'score' => '77.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '130.00', 'score' => '39.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '130.00', 'score' => '38.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '130.00', 'score' => '0.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],

                ['score_bracket' => '140.00', 'score' => '140.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '140.00', 'score' => '135.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '140.00', 'score' => '134.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '140.00', 'score' => '129.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '140.00', 'score' => '128.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '140.00', 'score' => '123.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '140.00', 'score' => '122.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()], // Updated to 1.75
                ['score_bracket' => '140.00', 'score' => '117.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()], // Updated to 1.75
                ['score_bracket' => '140.00', 'score' => '116.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '140.00', 'score' => '111.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '140.00', 'score' => '110.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '140.00', 'score' => '105.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '140.00', 'score' => '104.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '140.00', 'score' => '99.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '140.00', 'score' => '98.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '140.00', 'score' => '93.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '140.00', 'score' => '92.00', 'transmuted_grade' => '3.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '140.00', 'score' => '84.00', 'transmuted_grade' => '3.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '140.00', 'score' => '83.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '140.00', 'score' => '42.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '140.00', 'score' => '41.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '140.00', 'score' => '0.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],

                ['score_bracket' => '150.00', 'score' => '150.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '150.00', 'score' => '144.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '150.00', 'score' => '143.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '150.00', 'score' => '137.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '150.00', 'score' => '136.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '150.00', 'score' => '130.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '150.00', 'score' => '129.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '150.00', 'score' => '123.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '150.00', 'score' => '122.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '150.00', 'score' => '116.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '150.00', 'score' => '115.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '150.00', 'score' => '109.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '150.00', 'score' => '108.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '150.00', 'score' => '102.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '150.00', 'score' => '101.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '150.00', 'score' => '95.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '150.00', 'score' => '94.00', 'transmuted_grade' => '3.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '150.00', 'score' => '90.00', 'transmuted_grade' => '3.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '150.00', 'score' => '89.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '150.00', 'score' => '45.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '150.00', 'score' => '44.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '150.00', 'score' => '0.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],

                ['score_bracket' => '160.00', 'score' => '160.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '160.00', 'score' => '154.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '160.00', 'score' => '153.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '160.00', 'score' => '147.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '160.00', 'score' => '146.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '160.00', 'score' => '140.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '160.00', 'score' => '139.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '160.00', 'score' => '133.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '160.00', 'score' => '132.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '160.00', 'score' => '126.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '160.00', 'score' => '125.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '160.00', 'score' => '119.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '160.00', 'score' => '118.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '160.00', 'score' => '112.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '160.00', 'score' => '111.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '160.00', 'score' => '105.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '160.00', 'score' => '104.00', 'transmuted_grade' => '3.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '160.00', 'score' => '96.00', 'transmuted_grade' => '3.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '160.00', 'score' => '95.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '160.00', 'score' => '48.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '160.00', 'score' => '47.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '160.00', 'score' => '0.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],

                ['score_bracket' => '170.00', 'score' => '170.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '170.00', 'score' => '163.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '170.00', 'score' => '162.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '170.00', 'score' => '155.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '170.00', 'score' => '154.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '170.00', 'score' => '147.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '170.00', 'score' => '146.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '170.00', 'score' => '139.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '170.00', 'score' => '138.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '170.00', 'score' => '131.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '170.00', 'score' => '130.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '170.00', 'score' => '123.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '170.00', 'score' => '122.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '170.00', 'score' => '115.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '170.00', 'score' => '114.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '170.00', 'score' => '107.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '170.00', 'score' => '106.00', 'transmuted_grade' => '3.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '170.00', 'score' => '102.00', 'transmuted_grade' => '3.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '170.00', 'score' => '101.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '170.00', 'score' => '51.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '170.00', 'score' => '50.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '170.00', 'score' => '0.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],

                ['score_bracket' => '180.00', 'score' => '180.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '180.00', 'score' => '173.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '180.00', 'score' => '172.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '180.00', 'score' => '165.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '180.00', 'score' => '164.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '180.00', 'score' => '157.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '180.00', 'score' => '156.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '180.00', 'score' => '149.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '180.00', 'score' => '148.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '180.00', 'score' => '141.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '180.00', 'score' => '140.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '180.00', 'score' => '133.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '180.00', 'score' => '132.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '180.00', 'score' => '125.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '180.00', 'score' => '124.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '180.00', 'score' => '117.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '180.00', 'score' => '116.00', 'transmuted_grade' => '3.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '180.00', 'score' => '108.00', 'transmuted_grade' => '3.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '180.00', 'score' => '107.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '180.00', 'score' => '54.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '180.00', 'score' => '53.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '180.00', 'score' => '0.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],

                ['score_bracket' => '190.00', 'score' => '190.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '190.00', 'score' => '182.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '190.00', 'score' => '181.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '190.00', 'score' => '173.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '190.00', 'score' => '172.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '190.00', 'score' => '164.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '190.00', 'score' => '163.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '190.00', 'score' => '155.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '190.00', 'score' => '154.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '190.00', 'score' => '146.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '190.00', 'score' => '145.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '190.00', 'score' => '137.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '190.00', 'score' => '136.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '190.00', 'score' => '128.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '190.00', 'score' => '127.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '190.00', 'score' => '119.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '190.00', 'score' => '118.00', 'transmuted_grade' => '3.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '190.00', 'score' => '114.00', 'transmuted_grade' => '3.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '190.00', 'score' => '113.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '190.00', 'score' => '57.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '190.00', 'score' => '56.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '190.00', 'score' => '0.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],

                ['score_bracket' => '200.00', 'score' => '200.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '200.00', 'score' => '192.00', 'transmuted_grade' => '1.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '200.00', 'score' => '191.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '200.00', 'score' => '183.00', 'transmuted_grade' => '1.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '200.00', 'score' => '182.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '200.00', 'score' => '174.00', 'transmuted_grade' => '1.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '200.00', 'score' => '173.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '200.00', 'score' => '165.00', 'transmuted_grade' => '1.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '200.00', 'score' => '164.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '200.00', 'score' => '156.00', 'transmuted_grade' => '2.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '200.00', 'score' => '155.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '200.00', 'score' => '147.00', 'transmuted_grade' => '2.25', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '200.00', 'score' => '146.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '200.00', 'score' => '138.00', 'transmuted_grade' => '2.50', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '200.00', 'score' => '137.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '200.00', 'score' => '129.00', 'transmuted_grade' => '2.75', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '200.00', 'score' => '128.00', 'transmuted_grade' => '3.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '200.00', 'score' => '120.00', 'transmuted_grade' => '3.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '200.00', 'score' => '119.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '200.00', 'score' => '60.00', 'transmuted_grade' => '4.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '200.00', 'score' => '59.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],
                ['score_bracket' => '200.00', 'score' => '0.00', 'transmuted_grade' => '5.00', 'created_at' => now(), 'updated_at' => now()],
            ]);
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        //
    }
};
